services:
  qbittorrent-nox:
    build: .
    # for debugging
    #cap_add:
      #- SYS_PTRACE
    # additional arguments to `qbittorrent-nox`
    #command:
      #- --help
    container_name: qbittorrent-nox
    environment:
      #- PAGID=10000
      #- PGID=1000
      #- PUID=1000
      - QBT_LEGAL_NOTICE=${QBT_LEGAL_NOTICE}
      - QBT_VERSION=${QBT_VERSION}
      - QBT_TORRENTING_PORT=${QBT_TORRENTING_PORT}
      - QBT_WEBUI_PORT=${QBT_WEBUI_PORT}
      #- TZ=UTC
      #- UMASK=022
    image: qbittorrent-nox:${QBT_VERSION}
    ports:
      # for bittorrent traffic
      - ${QBT_TORRENTING_PORT}:${QBT_TORRENTING_PORT}/tcp
      - ${QBT_TORRENTING_PORT}:${QBT_TORRENTING_PORT}/udp
      # for WebUI
      - ${QBT_WEBUI_PORT}:${QBT_WEBUI_PORT}/tcp
    read_only: true
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - ${QBT_CONFIG_PATH}:/config
      - ${QBT_DOWNLOADS_PATH}:/downloads
